version: '3'
services:

  db:
    image: matheusvicentesn/postgres:1.0
    container_name: postgres
    restart: always
    tty: true
    ports:
      - '3333:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - postgres

  pgadmin:
    image: matheusvicentesn/pgadmin:1.0
    container_name: pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
